[project]
name = "play-redis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "axios>=0.4.0",
    "fastapi[standard]>=0.129.0",
    "redis>=7.2.0",
]
